# Same as full workflow (eg from fortio/gvi) but without the goreleaser step
name: "shared fortio workflows"

on:
    push:
      branches: [ main ] # put back once testing with pre-releases on branch is done.
      tags:
        - 'v*'
    pull_request:
      branches: [ main ]

jobs:
    call-gochecks:
        uses: fortio/workflows/.github/workflows/gochecks.yml@main
    call-codecov:
        uses: fortio/workflows/.github/workflows/codecov.yml@main
        secrets:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    call-codeql:
        uses: fortio/workflows/.github/workflows/codeql-analysis.yml@main
